CREATE TABLE IF NOT EXISTS public.book (
    id SERIAL PRIMARY KEY,
    author VARCHAR(255) NOT NULL,
    pages INTEGER NOT NULL,
    cost DOUBLE PRECISION NOT NULL,
    binding VARCHAR(255) NOT NULL
);
